language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

cache: pip

before_install:
    - "pip install poetry"

install:
    - "poetry install"

script:
    - "poetry run python -m py_compile *.py"
    - "poetry run pylint *.py -f colorized"
    - "poetry run pytest"
